// packages/react/src/components/Pagination.tsx
import * as React from 'react';

export interface PaginationProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
  total: number;
  current?: number;
  onChange?: (page: number) => void;
}

export const Pagination: React.FC<PaginationProps> = ({
  total,
  current = 1,
  onChange,
  className = '',
  ...props
}) => {
  const [page, setPage] = React.useState(current);

  const activePage = onChange !== undefined ? current : page;

  const getPages = (): (number | string)[] => {
    const pages: (number | string)[] = [];
    const maxVisible = 5;

    if (total <= maxVisible) {
      for (let i = 1; i <= total; i++) pages.push(i);
    } else {
      if (activePage <= 3) {
        for (let i = 1; i <= 4; i++) pages.push(i);
        pages.push('...');
        pages.push(total);
      } else if (activePage >= total - 2) {
        pages.push(1);
        pages.push('...');
        for (let i = total - 3; i <= total; i++) pages.push(i);
      } else {
        pages.push(1);
        pages.push('...');
        for (let i = activePage - 1; i <= activePage + 1; i++) pages.push(i);
        pages.push('...');
        pages.push(total);
      }
    }

    return pages;
  };

  const goTo = (p: number) => {
    if (p < 1 || p > total || p === activePage) return;
    if (onChange) {
      onChange(p);
    } else {
      setPage(p);
    }
  };

  return (
    <nav className={`cn-pagination ${className}`.trim()} aria-label="Pagination" {...props}>
      <button
        className="cn-pagination-item"
        onClick={() => goTo(activePage - 1)}
        disabled={activePage === 1}
        aria-label="Previous page"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16">
          <polyline points="15 18 9 12 15 6" />
        </svg>
      </button>
      {getPages().map((p, idx) =>
        p === '...' ? (
          <button
            key={idx}
            className="cn-pagination-item cn-pagination-ellipsis"
            disabled
            aria-label="More pages"
            aria-hidden="true"
            tabIndex={-1}
          >
            {p}
          </button>
        ) : (
          <button
            key={idx}
            className={`cn-pagination-item ${p === activePage ? 'cn-pagination-active' : ''}`.trim()}
            onClick={() => goTo(p)}
            aria-current={p === activePage ? 'page' : undefined}
          >
            {p}
          </button>
        )
      )}
      <button
        className="cn-pagination-item"
        onClick={() => goTo(activePage + 1)}
        disabled={activePage === total}
        aria-label="Next page"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16">
          <polyline points="9 18 15 12 9 6" />
        </svg>
      </button>
    </nav>
  );
};

Pagination.displayName = 'Pagination';

export default Pagination;

// packages/svelte/src/Pagination.svelte
<script>
import { createEventDispatcher } from 'svelte';

export let total = 1;
export let current = 1;
export let onChange = null;

const dispatch = createEventDispatcher();

function goToPage(page) {
	if (page < 1 || page > total || page === current) return;
	if (onChange) onChange(page);
	dispatch('change', { page });
}

function handleKeydown(event, page) {
	if (event.key === 'Enter' || event.key === ' ') {
		event.preventDefault();
		goToPage(page);
	}
}

$: pages = generatePages(total, current);

function generatePages(totalPages, currentPage) {
	if (totalPages <= 7) {
		return Array.from({ length: totalPages }, (_, i) => i + 1);
	}
	
	const pages = [];
	if (currentPage <= 4) {
		pages.push(1, 2, 3, 4, 5, '...', totalPages);
	} else if (currentPage >= totalPages - 3) {
		pages.push(1, '...', totalPages - 4, totalPages - 3, totalPages - 2, totalPages - 1, totalPages);
	} else {
		pages.push(1, '...', currentPage - 1, currentPage, currentPage + 1, '...', totalPages);
	}
	return pages;
}
</script>

<div class="cn-pagination">
	<button
		type="button"
		class="cn-pagination-item"
		disabled={current === 1}
		on:click={() => goToPage(current - 1)}
		on:keydown={(e) => handleKeydown(e, current - 1)}
		aria-label="Previous page"
	>
		<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
			<path d="M15 18l-6-6 6-6"/>
		</svg>
	</button>

	{#each pages as page}
		{#if page === '...'}
			<span class="cn-pagination-item cn-pagination-ellipsis" aria-label="More pages" aria-hidden="true">...</span>
		{:else}
			<button
				type="button"
				class="cn-pagination-item"
				class:cn-pagination-active={page === current}
				disabled={page === current}
				on:click={() => goToPage(page)}
				on:keydown={(e) => handleKeydown(e, page)}
				aria-label="Page {page}"
				aria-current={page === current ? 'page' : undefined}
			>
				{page}
			</button>
		{/if}
	{/each}

	<button
		type="button"
		class="cn-pagination-item"
		disabled={current === total}
		on:click={() => goToPage(current + 1)}
		on:keydown={(e) => handleKeydown(e, current + 1)}
		aria-label="Next page"
	>
		<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
			<path d="M9 18l6-6-6-6"/>
		</svg>
	</button>
</div>

<style>
.cn-pagination {
	display: flex;
	align-items: center;
	gap: 4px;
}

.cn-pagination-item {
	min-width: 32px;
	height: 32px;
	display: flex;
	align-items: center;
	justify-content: center;
	font-size: 12px;
	font-family: 'Outfit', sans-serif;
	font-weight: 500;
	border-radius: 10px;
	border: 1px solid rgba(255, 255, 255, 0.08);
	background: #111111;
	color: rgba(240, 237, 232, 0.5);
	cursor: pointer;
	transition: all 0.15s ease;
	padding: 0;
}

.cn-pagination-item:hover {
	border-color: rgba(255, 255, 255, 0.15);
	color: #f0ede8;
}

.cn-pagination-item.cn-pagination-active {
	background: #6b2323;
	border-color: #6b2323;
	color: #f0ede8;
}

.cn-pagination-item:disabled {
	opacity: 0.5;
	cursor: not-allowed;
}

.cn-pagination-ellipsis {
	cursor: default;
	border: none;
	background: transparent;
}

.cn-pagination-ellipsis:hover {
	border-color: transparent;
	color: rgba(240, 237, 232, 0.5);
}
</style>
