// packages/solid/src/components/Button.jsx
import { mergeProps } from 'solid-js';

function ButtonGroup(props) {
  const merged = mergeProps({ class: '' }, props);
  return (
    <div class={`cn-btn-group ${merged.class}`.trim()} {...merged}>
      {merged.children}
    </div>
  );
}

export function Button(props) {
  const merged = mergeProps({ variant: 'default', size: 'md', icon: false, class: '' }, props);

  const getClass = () => {
    const classes = ['cn-btn'];
    if (merged.variant !== 'default') classes.push(`cn-btn-${merged.variant}`);
    if (merged.size !== 'md') classes.push(`cn-btn-${merged.size}`);
    if (merged.icon) classes.push('cn-btn-icon');
    if (merged.class) classes.push(merged.class);
    return classes.join(' ');
  };

  return (
    <button
      type="button"
      class={getClass()}
      disabled={merged.disabled}
      {...merged}
    >
      {merged.children}
    </button>
  );
}

Button.Group = ButtonGroup;

export default Button;

// packages/react/src/components/Button.jsx
export default function Button({ 
  children, 
  variant = 'default', 
  size = 'md', 
  disabled = false,
  className = '',
  ...props 
}) {
  const variantClass = variant !== 'default' ? `cn-btn-${variant}` : '';
  const sizeClass = size !== 'md' ? `cn-btn-${size}` : '';

  return (
    <button 
      className={`cn-btn ${variantClass} ${sizeClass} ${className}`}
      disabled={disabled}
      {...props}
    >
      {children}
    </button>
  );
}
