// packages/solid/src/components/Dropdown.jsx
import { mergeProps, createSignal, Show, createEffect, onCleanup } from 'solid-js';

function DropdownItem(props) {
  const merged = mergeProps({ class: '' }, props);
  return (
    <div
      class={`cn-dropdown-item ${merged.class}`.trim()}
      onClick={merged.onClick}
      role="menuitem"
      tabIndex={0}
      {...merged}
    >
      {merged.icon && <span class="cn-dropdown-item-icon">{merged.icon}</span>}
      {merged.children}
    </div>
  );
}

function DropdownDivider() {
  return <div class="cn-dropdown-divider" role="separator" />;
}

export function Dropdown(props) {
  const merged = mergeProps({ class: '' }, props);
  const [isOpen, setIsOpen] = createSignal(false);
  let dropdownRef;

  const toggle = () => setIsOpen((prev) => !prev);
  const close = () => setIsOpen(false);

  createEffect(() => {
    const handleClickOutside = (e) => {
      if (dropdownRef && !dropdownRef.contains(e.target)) {
        close();
      }
    };

    if (isOpen()) {
      document.addEventListener('click', handleClickOutside);
    }

    return () => {
      document.removeEventListener('click', handleClickOutside);
    };
  });

  return (
    <div
      ref={dropdownRef}
      class={`cn-dropdown ${isOpen() ? 'cn-dropdown-open' : ''} ${merged.class}`.trim()}
      {...merged}
    >
      <div
        class="cn-dropdown-trigger"
        onClick={toggle}
        role="button"
        aria-haspopup="true"
        aria-expanded={isOpen()}
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            toggle();
          }
        }}
      >
        {merged.trigger}
      </div>
      <Show when={isOpen()}>
        <div class="cn-dropdown-menu" role="menu" onClick={close}>
          {merged.children}
        </div>
      </Show>
    </div>
  );
}

Dropdown.Item = DropdownItem;
Dropdown.Divider = DropdownDivider;

export default Dropdown;

// packages/react/src/components/Dropdown.jsx
import { useState, useEffect, useRef } from 'react';

export default function Dropdown({ 
  trigger,
  children,
  className = '' 
}) {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef(null);

  const toggle = () => setIsOpen((prev) => !prev);
  const close = () => setIsOpen(false);

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
        close();
      }
    };

    if (isOpen) {
      document.addEventListener('click', handleClickOutside);
    }

    return () => {
      document.removeEventListener('click', handleClickOutside);
    };
  }, [isOpen]);

  return (
    <div ref={dropdownRef} className={`cn-dropdown ${isOpen ? 'cn-dropdown-open' : ''} ${className}`}>
      <div className="cn-dropdown-trigger" onClick={toggle}>
        {trigger}
      </div>
      <div className="cn-dropdown-menu" onClick={close}>
        {children}
      </div>
    </div>
  );
}

export function DropdownItem({ children, onClick, className = '', ...props }) {
  return (
    <div className={`cn-dropdown-item ${className}`} onClick={onClick} {...props}>
      {children}
    </div>
  );
}
