// packages/solid/src/components/FormGroup.jsx
import { mergeProps, Show } from 'solid-js';

export function FormGroup(props) {
  const merged = mergeProps({
    required: false,
    class: ''
  }, props);

  return (
    <div class={`cn-form-group ${merged.class}`.trim()} {...merged}>
      <Show when={merged.label}>
        <label class="cn-form-label">
          {merged.label}
          <Show when={merged.required}>
            <span style={{ color: 'var(--cn-error-text)', 'margin-left': 'var(--cn-space-1)' }}>*</span>
          </Show>
        </label>
      </Show>
      {merged.children}
      <Show when={merged.error}>
        <div class="cn-form-error">{merged.error}</div>
      </Show>
      <Show when={!merged.error && merged.help}>
        <div class="cn-form-help">{merged.help}</div>
      </Show>
    </div>
  );
}

export default FormGroup;

// packages/react/src/components/FormGroup.tsx
import * as React from 'react';

export interface FormGroupProps extends React.HTMLAttributes<HTMLDivElement> {
  label?: React.ReactNode;
  error?: React.ReactNode;
  help?: React.ReactNode;
  required?: boolean;
}

export const FormGroup: React.FC<FormGroupProps> = ({
  children,
  label,
  error,
  help,
  required = false,
  className = '',
  ...props
}) => {
  return (
    <div className={`cn-form-group ${className}`.trim()} {...props}>
      {label && (
        <label className="cn-form-label">
          {label}
          {required && <span style={{ color: 'var(--cn-error-text)', marginLeft: 'var(--cn-space-1)' }}>*</span>}
        </label>
      )}
      {children}
      {error && <div className="cn-form-error">{error}</div>}
      {!error && help && <div className="cn-form-help">{help}</div>}
    </div>
  );
};

FormGroup.displayName = 'FormGroup';

export default FormGroup;
