// packages/solid/src/components/List.jsx
import { mergeProps, For, Show } from 'solid-js';

export function ListItem(props) {
  const merged = mergeProps({ clickable: false, class: '' }, props);
  return (
    <div
      class={`cn-list-item ${merged.clickable ? 'cn-list-item-clickable' : ''} ${merged.class}`.trim()}
      onClick={merged.onClick}
      role={merged.clickable ? 'button' : 'listitem'}
      tabIndex={merged.clickable ? 0 : undefined}
      {...merged}
    >
      <Show when={merged.icon}>
        <div class="cn-list-item-icon">{merged.icon}</div>
      </Show>
      <Show when={merged.title || merged.subtitle || merged.children}>
        <div class="cn-list-item-content">
          <Show when={merged.title}>
            <div class="cn-list-item-title">{merged.title}</div>
          </Show>
          <Show when={merged.subtitle}>
            <div class="cn-list-item-subtitle">{merged.subtitle}</div>
          </Show>
          {merged.children}
        </div>
      </Show>
      <Show when={merged.actions}>
        <div class="cn-list-item-actions">{merged.actions}</div>
      </Show>
    </div>
  );
}

export function List(props) {
  const merged = mergeProps({ class: '' }, props);
  return (
    <div class={`cn-list ${merged.class}`.trim()} role="list" {...merged}>
      {merged.children}
    </div>
  );
}

List.Item = ListItem;

export default List;

// packages/react/src/components/List.tsx
import * as React from 'react';

export interface ListProps extends React.HTMLAttributes<HTMLDivElement> {}

export interface ListItemProps extends React.HTMLAttributes<HTMLDivElement> {
  icon?: React.ReactNode;
  title?: string;
  subtitle?: string;
  actions?: React.ReactNode;
  clickable?: boolean;
}

export const List: React.FC<ListProps> = ({ children, className = '', ...props }) => {
  return (
    <div className={`cn-list ${className}`.trim()} role="list" {...props}>
      {children}
    </div>
  );
};

List.displayName = 'List';

export const ListItem: React.FC<ListItemProps> = ({
  children,
  icon,
  title,
  subtitle,
  actions,
  clickable = false,
  onClick,
  className = '',
  ...props
}) => {
  return (
    <div
      className={`cn-list-item ${clickable ? 'cn-list-item-clickable' : ''} ${className}`.trim()}
      onClick={onClick}
      role={clickable ? 'button' : 'listitem'}
      tabIndex={clickable ? 0 : undefined}
      {...props}
    >
      {icon && <div className="cn-list-item-icon">{icon}</div>}
      <div className="cn-list-item-content">
        {title && <div className="cn-list-item-title">{title}</div>}
        {subtitle && <div className="cn-list-item-subtitle">{subtitle}</div>}
        {children}
      </div>
      {actions && <div className="cn-list-item-actions">{actions}</div>}
    </div>
  );
};

ListItem.displayName = 'ListItem';

export default List;
