// packages/solid/src/components/Search.jsx
import { mergeProps, createSignal, Show, For, createEffect, onCleanup } from 'solid-js';

export function Search(props) {
  const merged = mergeProps({
    placeholder: 'Search...',
    items: [],
    onSelect: () => {}
  }, props);

  const [query, setQuery] = createSignal('');
  const [isOpen, setIsOpen] = createSignal(false);
  let searchRef;

  const filteredItems = () => {
    const q = query().toLowerCase();
    if (!q) return [];
    return merged.items.filter(item => {
      const title = typeof item === 'string' ? item : (item.title || item.label);
      const subtitle = item.subtitle || '';
      return title.toLowerCase().includes(q) || subtitle.toLowerCase().includes(q);
    });
  };

  const handleSelect = (item) => {
    const label = typeof item === 'string' ? item : (item.title || item.label);
    setQuery(label);
    setIsOpen(false);
    merged.onSelect(item);
  };

  createEffect(() => {
    const handleClickOutside = (e) => {
      if (searchRef && !searchRef.contains(e.target)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('click', handleClickOutside);
    return () => document.removeEventListener('click', handleClickOutside);
  });

  return (
    <div ref={searchRef} class={`cn-search ${isOpen() ? 'cn-search-open' : ''}`.trim()}>
      <svg class="cn-search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="11" cy="11" r="8" />
        <line x1="21" y1="21" x2="16.65" y2="16.65" />
      </svg>
      <input
        type="search"
        class="cn-input cn-search-input"
        placeholder={merged.placeholder}
        value={query()}
        onInput={(e) => {
          setQuery(e.target.value);
          setIsOpen(true);
        }}
        onFocus={() => setIsOpen(true)}
        role="combobox"
        aria-autocomplete="list"
        aria-expanded={isOpen()}
      />
      <Show when={isOpen()}>
        <div class="cn-search-results" role="listbox">
          {filteredItems().length > 0 ? (
            <For each={filteredItems()}>{(item) => (
              <div
                class="cn-search-result"
                onClick={() => handleSelect(item)}
                role="option"
              >
                <div class="cn-search-result-title">{typeof item === 'string' ? item : (item.title || item.label)}</div>
                <Show when={typeof item !== 'string' && item.subtitle}>
                  <div class="cn-search-result-subtitle">{item.subtitle}</div>
                </Show>
              </div>
            )}</For>
          ) : (
            <div class="cn-search-empty">No results found</div>
          )}
        </div>
      </Show>
    </div>
  );
}

export default Search;

// packages/react/src/components/Search.jsx
import { useState, useEffect, useRef } from 'react';

export default function Search({ 
  items = [],
  placeholder = 'Search...',
  onSelect,
  className = '' 
}) {
  const [query, setQuery] = useState('');
  const [isOpen, setIsOpen] = useState(false);
  const ref = useRef(null);

  const filtered = items.filter(item =>
    item.title.toLowerCase().includes(query.toLowerCase()) ||
    (item.subtitle && item.subtitle.toLowerCase().includes(query.toLowerCase()))
  );

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (ref.current && !ref.current.contains(e.target)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('click', handleClickOutside);
    return () => document.removeEventListener('click', handleClickOutside);
  }, []);

  const handleSelect = (item) => {
    setQuery(item.title);
    setIsOpen(false);
    onSelect?.(item);
  };

  return (
    <div ref={ref} className={`cn-search ${isOpen ? 'cn-search-open' : ''} ${className}`}>
      <svg className="cn-search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <circle cx="11" cy="11" r="8"></circle>
        <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
      </svg>
      <input
        type="text"
        className="cn-input cn-search-input"
        placeholder={placeholder}
        value={query}
        onChange={(e) => {
          setQuery(e.target.value);
          setIsOpen(true);
        }}
        onFocus={() => setIsOpen(true)}
      />
      {isOpen && filtered.length > 0 && (
        <div className="cn-search-results">
          {filtered.map((item, idx) => (
            <div
              key={idx}
              className="cn-search-result"
              onClick={() => handleSelect(item)}
            >
              <div className="cn-search-result-title">{item.title}</div>
              {item.subtitle && (
                <div className="cn-search-result-subtitle">{item.subtitle}</div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
