// packages/react/src/components/Dropdown.tsx
import * as React from 'react';

export interface DropdownProps extends React.HTMLAttributes<HTMLDivElement> {
  trigger: React.ReactNode;
}

export interface DropdownItemProps extends React.HTMLAttributes<HTMLDivElement | HTMLButtonElement> {
  icon?: React.ReactNode;
  divider?: boolean;
}

export const Dropdown: React.FC<DropdownProps> & {
  Item: React.FC<DropdownItemProps>;
  Divider: React.FC;
} = Object.assign(
  ({ trigger, children, className = '', ...props }: DropdownProps) => {
    const [isOpen, setIsOpen] = React.useState(false);
    const dropdownRef = React.useRef<HTMLDivElement>(null);

    const toggle = () => setIsOpen((prev) => !prev);
    const close = () => setIsOpen(false);

    React.useEffect(() => {
      const handleClickOutside = (e: MouseEvent) => {
        if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
          close();
        }
      };

      if (isOpen) {
        document.addEventListener('click', handleClickOutside);
      }

      return () => {
        document.removeEventListener('click', handleClickOutside);
      };
    }, [isOpen]);

    return (
      <div
        ref={dropdownRef}
        className={`cn-dropdown ${isOpen ? 'cn-dropdown-open' : ''} ${className}`.trim()}
        {...props}
      >
        <div
          className="cn-dropdown-trigger"
          onClick={toggle}
          role="button"
          aria-haspopup="true"
          aria-expanded={isOpen}
          tabIndex={0}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              toggle();
            }
          }}
        >
          {trigger}
        </div>
        <div className="cn-dropdown-menu" role="menu" onClick={close}>
          {children}
        </div>
      </div>
    );
  },
  {
    Item: ({ children, icon, onClick, className = '', ...props }: DropdownItemProps) => (
      <div
        className={`cn-dropdown-item ${className}`.trim()}
        onClick={onClick}
        role="menuitem"
        tabIndex={0}
        {...props}
      >
        {icon && <span className="cn-dropdown-item-icon">{icon}</span>}
        {children}
      </div>
    ),
    Divider: () => <div className="cn-dropdown-divider" role="separator" />,
  }
);

Dropdown.displayName = 'Dropdown';
Dropdown.Item.displayName = 'Dropdown.Item';
Dropdown.Divider.displayName = 'Dropdown.Divider';

export default Dropdown;

// packages/solid/src/components/Dropdown.jsx
import { mergeProps, createSignal, Show, createEffect, onCleanup } from 'solid-js';

function DropdownItem(props) {
  const merged = mergeProps({ class: '' }, props);
  return (
    <div
      class={`cn-dropdown-item ${merged.class}`.trim()}
      onClick={merged.onClick}
      role="menuitem"
      tabIndex={0}
      {...merged}
    >
      {merged.icon && <span class="cn-dropdown-item-icon">{merged.icon}</span>}
      {merged.children}
    </div>
  );
}

function DropdownDivider() {
  return <div class="cn-dropdown-divider" role="separator" />;
}

export function Dropdown(props) {
  const merged = mergeProps({ class: '' }, props);
  const [isOpen, setIsOpen] = createSignal(false);
  let dropdownRef;

  const toggle = () => setIsOpen((prev) => !prev);
  const close = () => setIsOpen(false);

  createEffect(() => {
    const handleClickOutside = (e) => {
      if (dropdownRef && !dropdownRef.contains(e.target)) {
        close();
      }
    };

    if (isOpen()) {
      document.addEventListener('click', handleClickOutside);
    }

    return () => {
      document.removeEventListener('click', handleClickOutside);
    };
  });

  return (
    <div
      ref={dropdownRef}
      class={`cn-dropdown ${isOpen() ? 'cn-dropdown-open' : ''} ${merged.class}`.trim()}
      {...merged}
    >
      <div
        class="cn-dropdown-trigger"
        onClick={toggle}
        role="button"
        aria-haspopup="true"
        aria-expanded={isOpen()}
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            toggle();
          }
        }}
      >
        {merged.trigger}
      </div>
      <Show when={isOpen()}>
        <div class="cn-dropdown-menu" role="menu" onClick={close}>
          {merged.children}
        </div>
      </Show>
    </div>
  );
}

Dropdown.Item = DropdownItem;
Dropdown.Divider = DropdownDivider;

export default Dropdown;
