// packages/react/src/components/Sidebar.tsx
import * as React from 'react';

export interface SidebarProps extends React.HTMLAttributes<HTMLElement> {
  header?: React.ReactNode;
  footer?: React.ReactNode;
}

export interface SidebarItemProps extends React.HTMLAttributes<HTMLAnchorElement | HTMLDivElement> {
  active?: boolean;
  icon?: React.ReactNode;
  href?: string;
}

export const Sidebar: React.FC<SidebarProps> & {
  Item: React.FC<SidebarItemProps>;
} = Object.assign(
  ({ header, footer, children, className = '', ...props }: SidebarProps) => {
    return (
      <aside className={`cn-sidebar ${className}`.trim()} {...props}>
        {header && <div className="cn-sidebar-header">{header}</div>}
        <div className="cn-sidebar-nav">{children}</div>
        {footer && <div className="cn-sidebar-footer">{footer}</div>}
      </aside>
    );
  },
  {
    Item: ({ children, active = false, icon, href, className = '', ...props }: SidebarItemProps) => {
      const content = (
        <>
          {icon && <span className="cn-sidebar-item-icon">{icon}</span>}
          {children}
        </>
      );

      if (href) {
        return (
          <a
            href={href}
            className={`cn-sidebar-item ${active ? 'cn-sidebar-active' : ''} ${className}`.trim()}
            role="menuitem"
            {...(props as React.AnchorHTMLAttributes<HTMLAnchorElement>)}
          >
            {content}
          </a>
        );
      }

      return (
        <div
          className={`cn-sidebar-item ${active ? 'cn-sidebar-active' : ''} ${className}`.trim()}
          role="menuitem"
          {...(props as React.HTMLAttributes<HTMLDivElement>)}
        >
          {content}
        </div>
      );
    },
  }
);

Sidebar.displayName = 'Sidebar';
(Sidebar.Item as React.FC<SidebarItemProps> & { displayName?: string }).displayName = 'SidebarItem';

export default Sidebar;

// packages/solid/src/components/Sidebar.jsx
import { mergeProps, For, Show } from 'solid-js';

function SidebarItem(props) {
  const merged = mergeProps({ active: false, class: '' }, props);

  const content = (
    <>
      <Show when={merged.icon}>
        <span class="cn-sidebar-item-icon">{merged.icon}</span>
      </Show>
      {merged.children}
    </>
  );

  if (merged.href) {
    return (
      <a
        href={merged.href}
        class={`cn-sidebar-item ${merged.active ? 'cn-sidebar-active' : ''} ${merged.class}`.trim()}
        role="menuitem"
        {...merged}
      >
        {content}
      </a>
    );
  }

  return (
    <div
      class={`cn-sidebar-item ${merged.active ? 'cn-sidebar-active' : ''} ${merged.class}`.trim()}
      role="menuitem"
      {...merged}
    >
      {content}
    </div>
  );
}

export function Sidebar(props) {
  const merged = mergeProps({ class: '' }, props);

  return (
    <aside class={`cn-sidebar ${merged.class}`.trim()} {...merged}>
      <Show when={merged.header}>
        <div class="cn-sidebar-header">{merged.header}</div>
      </Show>
      <div class="cn-sidebar-nav">
        {merged.children}
      </div>
      <Show when={merged.footer}>
        <div class="cn-sidebar-footer">{merged.footer}</div>
      </Show>
    </aside>
  );
}

Sidebar.Item = SidebarItem;

export default Sidebar;
