// packages/react/src/components/Stack.tsx
import * as React from 'react';

export interface StackProps extends React.HTMLAttributes<HTMLDivElement> {
  spacing?: '1' | '2' | '4' | '6';
}

export const Stack: React.FC<StackProps> = ({
  children,
  spacing = '4',
  className = '',
  ...props
}) => {
  return (
    <div
      className={`cn-stack cn-stack-${spacing} ${className}`.trim()}
      {...props}
    >
      {children}
    </div>
  );
};

Stack.displayName = 'Stack';

export const HStack: React.FC<StackProps> = ({
  children,
  spacing = '4',
  className = '',
  ...props
}) => {
  return (
    <div
      className={`cn-hstack cn-hstack-${spacing} ${className}`.trim()}
      {...props}
    >
      {children}
    </div>
  );
};

HStack.displayName = 'HStack';

export interface DividerProps extends React.HTMLAttributes<HTMLHRElement> {
  orientation?: 'horizontal' | 'vertical';
}

export const Divider: React.FC<DividerProps> = ({
  className = '',
  orientation = 'horizontal',
  style,
  ...props
}) => {
  const dividerStyle: React.CSSProperties = orientation === 'vertical'
    ? { width: '1px', height: 'auto', minHeight: '100%', borderRight: 'none', borderBottom: '1px solid var(--cn-border)', ...style }
    : { height: '1px', border: 'none', backgroundColor: 'var(--cn-border)', ...style };

  return (
    <hr
      className={`cn-divider ${className}`.trim()}
      style={dividerStyle}
      role="separator"
      {...props}
    />
  );
};

Divider.displayName = 'Divider';

export default Stack;

// packages/solid/src/components/Stack.jsx
import { mergeProps } from 'solid-js';

export function Stack(props) {
  const merged = mergeProps({ spacing: '4', class: '' }, props);
  return (
    <div class={`cn-stack cn-stack-${merged.spacing} ${merged.class}`.trim()} {...merged}>
      {merged.children}
    </div>
  );
}

export function HStack(props) {
  const merged = mergeProps({ spacing: '4', class: '' }, props);
  return (
    <div class={`cn-hstack cn-hstack-${merged.spacing} ${merged.class}`.trim()} {...merged}>
      {merged.children}
    </div>
  );
}

export function Divider(props) {
  const merged = mergeProps({ orientation: 'horizontal', class: '' }, props);

  const dividerStyle = merged.orientation === 'vertical'
    ? 'width: 1px; height: auto; min-height: 100%; border-right: none; border-bottom: 1px solid var(--cn-border);'
    : 'height: 1px; border: none; background-color: var(--cn-border);';

  return (
    <hr
      class={`cn-divider ${merged.class}`.trim()}
      style={dividerStyle}
      role="separator"
      {...merged}
    />
  );
}

export default Stack;
